export default {
    antenna: [
        "8-Ball",
        "Dollar Sign",
        "Gingerbread Man",
        "Gold Nugget",
        "Heart",
        "Horseshoe",
        "Lightning Bolt",
        "Peace Sign",
        "Saturn",
        "Skull",
        "Smiley Face",
        "Snowman",
        "Soccer Ball",
        "Star",
        "Sweet Tooth",
        "Tennis Ball",
        "UFO",
        "Algeria",
        "Argentina",
        "Australia",
        "Austria",
        "Belgium",
        "Bosnia and Herzegovina",
        "Brazil",
        "Bulgaria",
        "Cameroon",
        "Canada",
        "Cape Verde Islands",
        "Chile",
        "China",
        "Colombia",
        "Congo",
        "Costa Rica",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Ecuador",
        "El Salvador",
        "England",
        "Equatorial Guinea",
        "Finland",
        "France",
        "Germany",
        "Ghana",
        "Greece",
        "Guatemala",
        "Guinea",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Ireland",
        "Israel",
        "Italy",
        "Côte d'Ivoire",
        "Jamaica",
        "Japan",
        "Kenya",
        "Luxembourg",
        "Malaysia",
        "Malta",
        "Mexico",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Nigeria",
        "Northern Ireland",
        "Norway",
        "Pakistan",
        "Panama",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Romania",
        "Scotland",
        "Senegal",
        "Serbia",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "South Africa",
        "South Korea",
        "Spain",
        "Sweden",
        "Switzerland",
        "Chinese Taipei",
        "Thailand",
        "Tunisia",
        "Turkey",
        "United Arab Emirates",
        "United Kingdom",
        "Ukraine",
        "Uruguay",
        "United States",
        "Venezuela",
        "Vietnam",
        "Wales",
        "Yemen",
        "Blacklight: Retribution",
        "Edge Of Space",
        "Fenix Rage",
        "Jolly Roger",
        "Shadowgate",
        "Strike Vector EX",
        "Team Fat",
        "Twitch",
        "Unreal",
        "Warframe",
        "Country Flags",
        "Blue Chequered Flag",
        "Camo Flag",
        "Safety Flag",
        "Psyonix",
        "Blacklight",
        "Sri Lanka",
        "Dave's Bread",
        "Chick Magnet",
        "Cupcake",
        "Disconnect",
        "Donut",
        "Eyeball",
        "Unreal Tournament - Flak Shell",
        "Foam Finger",
        "Giant Panda",
        "Piñata",
        "Waffle",
        "Afghanistan",
        "Albania",
        "American Samoa",
        "Angola",
        "Armenia",
        "Azerbaijan",
        "Bangladesh",
        "Belarus",
        "Benin",
        "Bolivia",
        "Burkina Faso",
        "Burma",
        "Burundi",
        "Cambodia",
        "Chad",
        "Congo DR",
        "Cuba",
        "Dominican Republic",
        "Egypt",
        "Eritrea",
        "Estonia",
        "Ethiopia",
        "Gabon",
        "Georgia",
        "Guam",
        "Haiti",
        "Iraq",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Liberia",
        "Libya",
        "Lithuania",
        "Macedonia",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Moldova",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "North Mariana Islands",
        "Namibia",
        "Nepal",
        "Republic of Niger",
        "North Korea",
        "Oman",
        "Palestine",
        "Papua New Guinea",
        "Paraguay",
        "Puerto Rico",
        "Qatar",
        "Rwanda",
        "Saudi Arabia",
        "Sierra Leone",
        "Somalia",
        "South Sudan",
        "Sudan",
        "Syria",
        "Tajikistan",
        "Tanzania",
        "Togo",
        "Trinidad and Tobago",
        "Turkmenistan",
        "Uganda",
        "US Virgin Islands",
        "Uzbekistan",
        "Zambia",
        "Zimbabwe",
        "Unreal Tournament-Blue",
        "Unreal Frag Center",
        "Unreal Tournament - Red",
        "Unreal Tournament (Classic)",
        "Unreal Tournament 2004",
        "Unreal Tournament",
        "Rainbow Flag",
        "White Flag",
        "Community Flags",
        "LIRIK",
        "Spooky1611",
        "Team PowA",
        "YouTube Gaming",
        "Central Africa Republic",
        "Moai",
        "Chivalry - Agatha Knights",
        "Chivalry - Mason Order",
        "Community",
        "Moderator",
        "(Reward) Linguist",
        "Anne Munition",
        "EMD1",
        "itmeJP",
        "Saudi Gamer",
        "The Attack",
        "ESL",
        "ESL Champ",
        "MLG",
        "Tourney Champ",
        "Video Games",
        "Angry Army",
        "Bahrain",
        "Belize",
        "Bhutan",
        "Botswana",
        "Comoros",
        "Djibouti",
        "East Timor",
        "Fiji",
        "Gambia",
        "Guyana",
        "Kosovo",
        "Lesotho",
        "Macau",
        "Mauritius",
        "Puntland",
        "Réunion",
        "Solomon Islands",
        "Somaliland",
        "Suriname",
        "Swaziland",
        "Western Sahara",
        "Serious Gaming",
        "Razer",
        "Calavera",
        "Retro Ball - Urban",
        "Retro Ball - Utopia",
        "Retro Ball - Wasteland",
        "Fuzzy Brute",
        "Fuzzy Vamp",
        "Polaris",
        "Achievement Hunter",
        "Funhaus",
        "Rooster Teeth",
        "Bomb Pole",
        "Radioactive",
        "NeoGAF",
        "lolRenaynay",
        "Reddit Snoo",
        "Reddit",
        "Oddworld-Necrum",
        "Oddworld-RuptureFarms",
        "RL Garage",
        "Candy Cane",
        "Holiday Gift",
        "Day TV",
        "The Game Awards-Statue",
        "Portal-Aperture Laboratories",
        "Portal-Cake Sticker",
        "PC Gamer",
        "Fallout-Vault Boy",
        "Oddworld-Abe",
        "Oddworld-Molluck",
        "Portal-Companion Cube",
        "Warframe-Chroma",
        "Warframe-Loki",
        "Warframe-Excalibur",
        "Portal-Wheatley",
        "The Game Awards-Logo",
        "Portal-PotatOS",
        "Something Awful",
        "Destructoid",
        "Gamespot",
        "Operation Sports",
        "Gold Glove",
        "Tonga",
        "Gfinity",
        "Witcher Medallion",
        "Parrot",
        "Balloon Dog",
        "Alien",
        "Rocket",
        "Candle",
        "Hula Girl",
        "Rubber Duckie",
        "deadmau5",
        "Flower-Daisy",
        "Flower-Orchid",
        "Flower-Rose",
        "Flower-Sunflower",
        "Flower-Tulip",
        "Venus Flytrap",
        "Genie Lamp",
        "9GAG",
        "Disco Ball",
        "IGN",
        "Batman",
        "Superman",
        "Wonder Woman",
        "NVIDIA",
        "Euro Truck Simulator Rig",
        "AbleGamers",
        "Panic Button",
        "Andorra",
        "Anguilla",
        "Antigua&Barbuda",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Bermuda",
        "British Virgin Islands",
        "Cayman Islands",
        "Cook Islands",
        "Curacao",
        "Dominica",
        "Falkland Islands",
        "Faroe Islands",
        "Gibraltar",
        "Isle Of Man",
        "Kiribati",
        "Maldives",
        "Marshall Islands",
        "Micronesia",
        "New Caledonia",
        "Palau",
        "Saint Kitts&Nevis",
        "Saint Lucia",
        "Saint Vincent",
        "Samoa",
        "San Marino",
        "Sao Tome",
        "Seychelles",
        "Tahiti",
        "Turks&Caicos",
        "Vanuatu",
        "Vatican City",
        "Grenada",
        "Montserrat",
        "Goat Simulator-Goatenna",
        "Rocket Beans TV",
        "PAX",
        "Penny Arcade",
        "Div",
        "Goat Simulator-G2",
        "Worms W.M.D. Grenade",
        "Worms W.M.D",
        "Spartan Sam",
        "4Player Network",
        "Shacknews",
        "Atlanta Hawks",
        "Boston Celtics",
        "Brooklyn Nets",
        "Charlotte Hornets",
        "Chicago Bulls",
        "Cleveland Cavaliers",
        "Dallas Mavericks",
        "Denver Nuggets",
        "Detroit Pistons",
        "Golden State Warriors",
        "Houston Rockets",
        "Indiana Pacers",
        "Los Angeles Clippers",
        "Los Angeles Lakers",
        "Memphis Grizzlies",
        "Miami Heat",
        "Milwaukee Bucks",
        "Minnesota Timberwolves",
        "NBA",
        "New Orleans Pelicans",
        "New York Knicks",
        "Oklahoma City Thunder",
        "Orlando Magic",
        "Philadelphia 76ers",
        "Phoenix Suns",
        "Portland Trail Blazers",
        "Sacramento Kings",
        "San Antonio Spurs",
        "Toronto Raptors",
        "Utah Jazz",
        "Washington Wizards",
        "NBA Flags",
        "Dying Light",
        "Hot Dog",
        "ScrewAttack",
        "Headlander-Starcophagus",
        "Dying Light-Gas Tank",
        "Discord",
        "Fuzzy Skull",
        "Trident",
        "Seastar",
        "Harpoon",
        "RLCS",
        "SDMN FC",
        "Vikkstar",
        "Satellite",
        "Nutcracker",
        "NoClip",
        "NZXT",
        "Hot Wheels",
        "Treasure Hunt",
        "Easter Egg",
        "J!NX",
        "Loot Crate",
        "Monstercat",
        "Morty",
        "Rick",
        "X Games",
        "Lollipop",
        "Koinobori",
        "Cuckoo Clock",
        "Jon Sandman",
        "Macaron",
        "Peppermint",
        "Arachnotenna",
        "Shadow Witch",
        "Holiday Stocking",
        "NVIDIA SHIELD",
        "Dandelion Seed",
        "Brunei",
        "Monaco",
        "Nauru",
        "Tuvalu",
        "Warm Watermelon",
        "Siiick Reads",
        "Mr Toasty",
        "Monstercat",
        "WWE Monday Night RAW",
        "WWE NXT",
        "WWE",
        "WWE SmackDown Live",
        "Uncaged Cat",
        "Instinct",
        "Pegboard Nerds",
        "Stonebank",
        "Uncaged",
        "WWE WrestleMania 34",
        "Bubble Wand",
        "Anna Yvette",
        "Intercom",
        "Koven",
        "Slippy",
        "Protostar",
        "Jurassic Park",
        "Jurassic World",
        "S Watercolour",
        "InGen",
        "SARPBC-10",
        "Bad Computer",
        "Dion Timmer",
        "Duumu",
        "Stephen Walking",
        "Skyelle",
        "Sundial",
        "Soupandreas",
        "Aiobahn",
        "Calculated",
        "Mage Glass I",
        "Mage Glass II",
        "Mage Glass III",
        "Hot Wheels 50th",
        "Darren Styles",
        "Dougal",
        "Gammer",
        "Infected Mushroom",
        "Muzzy",
        "Pixel Terror",
        "Tokyo Machine",
        ],
        body: [
            "Backfire",
            "Breakout",
            "Octane",
            "Paladin",
            "Road Hog",
            "Gizmo",
            "Sweet Tooth",
            "X-Devil",
            "Hotshot",
            "Merc",
            "Venom",
            "Takumi",
            "Dominus",
            "Scarab",
            "Zippy",
            "DeLorean Time Machine",
            "Ripper",
            "Grog",
            "Armadillo",
            "Hogsticker",
            "Batmobile",
            "Dominus GT",
            "X-Devil Mk2",
            "Masamune",
            "Marauder",
            "Aftershock",
            "Takumi RX-T",
            "Road Hog XL",
            "Esper",
            "Breakout Type-S",
            "Proteus",
            "Triton",
            "Vulcan",
            "Octane ZSR",
            "Twin Mill III",
            "Bone Shaker",
            "Endo",
            "Ice Charger",
            "Mantis",
            "Jäger 619 RS",
            "Imperator DT5",
            "Samurai",
            "Centio V17",
            "Animus GP",
            "Werewolf",
            "'70 Dodge Charger R/T",
            "'99 Nissan Skyline GT-R R34",
            "Samus's Gunship",
            "Mario NSR",
            "The Dark Knight Rises Tumbler",
            "'89 Batmobile",
            "Twinzer",
            "Jurassic Jeep® Wrangler",
            "Fast 4WD",
            "MR11",
            "Gazella GT",
            "Cyclone",
            "Merc",
            "Mystery Item",
            "Maverick",
            "Maverick G1",
            "Maverick GXT",
        ],
        "rocket boost": [
            "Gold Rush",
            "Bubbles",
            "Confetti",
            "Datastream",
            "Flamethrower",
            "Flamethrower Blue",
            "Flamethrower Green",
            "Flamethrower Pink",
            "Flamethrower Purple",
            "Flamethrower Red",
            "Flowers",
            "Sacred",
            "Ion",
            "Ion Green",
            "Ion Pink",
            "Ion Purple",
            "Ion Red",
            "Ion Yellow",
            "Money",
            "Plasma",
            "Thermal",
            "Thermal Blue",
            "Thermal Green",
            "Thermal Pink",
            "Thermal Purple",
            "Thermal Yellow",
            "Rainbow",
            "Slime",
            "Snowflakes",
            "Sparkles",
            "Standard",
            "Standard Blue",
            "Standard Pink",
            "Standard Purple",
            "Standard Yellow",
            "Sweet Tooth",
            "Hydro",
            "Nitrous",
            "Burnout",
            "Lightning",
            "Accelerato",
            "Nuts & Bolts",
            "Battle-Stars",
            "Candy Corn",
            "OutaTime",
            "Xmas",
            "Portal - Conversion Gel",
            "Portal - Propulsion Gel",
            "Portal - Repulsion Gel",
            "Sandstorm",
            "Overcharge",
            "Blamite Overthruster",
            "UV Turret",
            "Imulsion",
            "Batmobile",
            "Feather",
            "Hearts",
            "Pixel Fire",
            "Polygonal",
            "Toon Smoke",
            "Trinity",
            "Frostbite",
            "Flamethrower Yellow",
            "Standard Green",
            "Magmus",
            "Season 2 - Challenger",
            "Season 2 - Champion",
            "Season 2 - Prospect",
            "Season 2 - Star",
            "Ink",
            "Treasure",
            "Cold Fusion",
            "Lightning Yellow",
            "Netherworld",
            "Hypernova",
            "Xenosplash",
            "Dark Matter",
            "Tachyon",
            "Proton",
            "Magic Missile",
            "Taco",
            "Hexphase",
            "Helios",
            "Neo-Thermal",
            "Interdimensional GB",
            "Super Star",
            "Power-Shot",
            "Scary Pumpkin",
            "Wave Beam",
            "Fractal Fire",
            "Winter Storm",
            "Yuletide",
            "Tsunami Beam",
            "Toon Sketch",
            "Geo Soul",
            "Springtime Flowers",
            "Blast Ray",
            "The Dark Knight Rises Tumbler",
            "'89 Batmobile",
            "Speed Force",
            "Comet",
            "Popcorn",
            "Torrent",
            "Enchanter",
            "Sun Ray",
            "Cirrus",
            "Virtual Wave",
            "Cloudburst I",
            "Cloudburst II",
            "Cloudburst III",
            "Hot Rod",
            "Season 8 - Bronze",
            "Season 8 - Diamond",
            "Season 8 - Gold",
            "Season 8 - Silver",
            "Season 8 - Champion",
            "Season 8 - Platinum",
        ],
        decal: [
            "Flames",
            "Lightning",
            "Skulls",
            "Stars",
            "Stripes",
            "Tech",
            "Wings",
            "Dots",
            "Tagged",
            "Copycat",
            "Reiko",
            "Gaki",
            "Crazy-8",
            "Chaser",
            "Scorpions",
            "Tats",
            "Hearts",
            "Tiger",
            "Leopard",
            "Bomani",
            "Tribal",
            "Caboodle",
            "Callous",
            "Derby Girl",
            "Shot Fox",
            "Spikes",
            "Bomber",
            "Lepus",
            "Cyclops",
            "Ockie",
            "Protractor",
            "Sunburst",
            "Techno",
            "Anubis",
            "Combo",
            "Distortion",
            "Vector",
            "Dragon Lord",
            "Dot Rush",
            "Racer",
            "Snakeskin",
            "Warlock",
            "Flex",
            "Nine Lives",
            "Dot Matrix",
            "Dominus: Dot Matrix",
            "Pollo Caliente",
            "Debugged",
            "Hyper",
            "Wildfire",
            "Road Rage",
            "Junk Food",
            "Royalty",
            "Arsenal",
            "Otaku",
            "DJ Sushi",
            "Space Trip",
            "Skullface",
            "Party-Chan",
            "Inked",
            "Blackwork",
            "Rockat",
            "MIRV",
            "Seismic",
            "Shank",
            "Super F3",
            "Kaiju",
            "Mouse Cat",
            "Neo",
            "Pegasus",
            "Big Buck",
            "Vagabond",
            "Ruffian",
            "Safari",
            "Flower Power",
            "Arrowhead",
            "Mystery Universal Decal",
            "Iris",
            "Hyper-Flight",
            "Python",
            "Shockwave",
            "Horus",
            "Muerto",
            "Playtime",
            "Heatwave",
            "Labyrinth",
            "Parallax",
            "Slipstream",
            "Carbonated",
            "X-Devil: Dot Matrix",
            "Arcana",
            "Whizzle",
            "Shibuya",
            "Narwhal",
            "Cuttle Time",
            "Fathom",
            "Daddy-O",
            "Modus Bestia",
            "Makai",
            "Fugu",
            "Ragnarok",
            "Crash Dive",
            "Ladybug",
            "Falchion",
            "Turbo",
            "Tiger Shark",
            "MG-88",
            "Mondo",
            "Shisa",
            "Oni",
            "Roadkill",
            "Hi-Tech",
            "Kilowatt",
            "Mean Streak",
            "Interceptor",
            "Namesake",
            "Peace",
            "Gobo",
            "Biomass",
            "Hexed",
            "Spectre",
            "ARC",
            "Cryo-Flames",
            "Medic",
            "Space Worm",
            "Combat",
            "Maximon",
            "Armada",
            "Funny Book",
            "Cobra",
            "Heiwa",
            "Kawaii",
            "Griffon",
            "Starstruck",
            "Pro-Street",
            "Inferno",
            "Bone Jack",
            "Suji",
            "Unmasked",
            "Super RX-T",
            "Primo",
            "Overline",
            "Pyro",
            "Javelin",
            "Dyno",
            "Cupcake",
            "Tora",
            "20XX",
            "Speedster",
            "Crazy Sandwich",
            "Rally",
            "CDXL",
            "Cyrus",
            "Circuit Pro",
            "RLCS",
            "Rakugaki",
            "Battleworn",
            "Maxx",
            "Kaze",
            "Uproar",
            "Roasted",
            "Mobo",
            "Sticker Bomb",
            "MDGA",
            "Jiangshi",
            "Buzz Kill",
            "Aqueous",
            "Clean Cut",
            "Chusho",
            "Bubbly",
            "Funnybook",
            "L-ITA 99",
            "Flagman",
            "MiNT",
            "Echo-Pulse",
            "Zhangtek",
            "Necro",
            "Monza",
            "Spatter",
            "Lone Wolf",
            "SWT-T",
            "Slimline",
            "Feral",
            "Arcadia",
            "Big Scratches",
            "Pro",
            "Anticlipse",
            "Shapeshifter",
            "NBP",
            "Righteous Sun",
            "Critters",
            "Monstercat",
            "BOO!",
            "Smore'd",
            "Splatter",
            "Odd Fish",
            "Overhaul",
            "The Summit",
            "Kraken",
            "Storm Warning",
            "Euphoria",
            "Callous Bros.",
            "Widow's Web",
            "Stitches",
            "Afterlife",
            "Thanatos",
            "Octane: Turtle Tribe",
            "Breakout: Bobcat",
            "Breakout: 9 Lives",
            "Breakout: Sneaky Slither",
            "Staredown",
            "NNTR",
            "Octane ZSR: Mechaceph",
            "Octane: Chantico",
            "Mummified",
            "Hammerhead",
            "Alameda Twin",
            "Good Graces",
            "Sinclair",
            "Wheelman",
            "Twisted Tree",
            "Cold Sweater",
            "Animus GP: Peacock",
            "Pollinator",
            "Machina",
            "Splashback",
            "Polar Force",
            "Home Stretch",
            "2Cool",
            "Cold Front",
            "The Clutch",
            "2Bold",
            "2Tuff",
            "Christmas Tree",
            "Holiday Deco",
            "Gigapede",
            "Rad Reindeer",
            "Chameleon",
            "Leviathan",
            "Rose King",
            "Athena",
            "Windswept",
            "Mosher",
            "Mister Monsoon",
            "Jäger 619 RS: Shark Tooth",
            "Hip-Hop",
            "Jäger 619 RS: StarLighter",
            "XVI",
            "XVIII",
            "Dominus: Templar",
            "Octane: Island King",
            "Octane: Space Cadet",
            "X-Devil: Devil's Advocate",
            "Froggy",
            "Glyphtrix",
            "Tiger Tiger",
            "Dominus: Proptosis",
            "Fantasmo",
            "Royal Tyrant",
            "Octane: Dr. Thrash",
            "Min-Spec",
            "Dune Racer",
            "Sundae",
            "Merc: B.B. Wolf",
            "Breakout: Astaroth",
            "Egged",
            "ShapeRacer",
            "Storm Watch",
            "Kaleidoscope",
            "Ripped Comic",
            "Camo",
            "Wonder Woman",
            "Trigon",
            "Superman",
            "Cyborg",
            "Green Lantern",
            "The Flash",
            "Batman",
            "Swirls",
            "Aquaman",
            "Green Arrow",
            "Dissolver",
            "Thunderspeck",
            "Star Swash",
            "Midnight D",
            "Motor Monster",
            "AWD",
            "Trace Racer",
            "Radium",
            "Breakout: Nice Shot",
            "Dominus: Savage",
            "Octane: Nice Shot",
            "Fire God",
            "Streamline",
            "Boo-ya!",
            "Slimed",
            "Breakout: CRL Western",
            "Dominus: CRL Eastern",
            "Dominus: CRL Southern",
            "Octane: CRL Northern",
            "Partly Cloudy",
            "Octane: Noooo!",
            "MR11: Diecast",
            "MR11: Hot Wheels Race Team",
            "MR11: 50th Anniversary",
            "Cyclone: Whiteout",
            "Cyclone: Bat Boy",
            "Cyclone: L-ITA 99",
            "Cyclone: Sliver",
            "Cyclone: Flames",
            "Cyclone: Stripes",
            "Humble Pie",
            "Mainframe",
            "Fast 4WD: 50th Anniversary",
            "Fast 4WD: Sleek",
            "Fast 4WD: Hot Wheels Race Team",
            "Fast 4WD: Diecast",
            "Octane: RC Rivals",
            "Dominus: RC Rivals",
            "Stripe Racer",
            "Jetstream",
            "Block Trim",
            "Baller",
            "Gale-Fire",
            "Gazella GT: 50th Anniversary",
            "Gazella GT: Sleek",
            "MR11: Sleek",
            "Gazella GT: Diecast",
            "Gazella GT: Hot Wheels Race Team",
            "Sara Skinner",
            "Breakout: Ripped Comic",
        ],
        "engine audio": [
            "Aftershock",
            "Esper",
            "Armadillo",
            "Bone Shaker",
            "Breakout Type-S",
            "Breakout Type-S v2",
            "Triton",
            "OEM-A",
            "OEM-A v2",
            "OEM-D",
            "OEM-D v2",
            "OEM-C",
            "OEM-C v2",
            "OEM-B",
            "OEM-B v2",
            "Batmobile",
            "Dominus GT",
            "Dominus GT v2",
            "Endo",
            "Animus GP",
            "Mantis",
            "Vulcan",
            "DeLorean Time Machine",
            "Grog",
            "Ice Charger",
            "Centio V17",
            "Marauder",
            "Masamune",
            "Proteus",
            "Octane ZSR",
            "Octane ZSR v2",
            "Road Hog XL",
            "Sweet Tooth",
            "Takumi RX-T",
            "Takumi RX-T v2",
            "Twin Mill III",
            "HogSticker",
            "X-Devil Mk2",
            "X-Devil Mk2 v2",
            "Triton v2",
            "Proteus v2",
            "Marauder v2",
            "Takumi",
            "Road Hog XL v2",
            "Dominus",
            "Ripper",
            "Scarab",
            "Zippy",
            "Maverick",
            "Jäger 619 RS",
            "Werewolf",
            "Aftershock v2",
            "Imperator DT5",
            "Samurai",
            "NSR",
            "Samus's Gunship",
            "'70 Dodge Charger R/T",
            "'99 Nissan Skyline GT-R R34",
            "The Dark Knight Rises Tumbler",
            "'89 Batmobile",
            "Jurassic Jeep® Wrangler",
            "Twinzer",
            "Motormouth",
            "Go-Kart",
            "Muscle Car",
            "Cyclone",
            "Fast 4WD",
            "MR11",
            "Gazella GT",
        ],
        "goal explosion": [
            "Classic",
            "Electroshock",
            "Fireworks",
            "Sub-Zero",
            "Hellfire",
            "Standard Green",
            "Standard Orange",
            "Standard Pink",
            "Standard Purple",
            "Vampire Bat",
            "Party Time",
            "Dueling Dragons",
            "Popcorn",
            "Poly Pop",
            "Reaper",
            "Happy Holidays",
            "Butterflies",
            "Toon",
            "Ballistic",
            "Atomizer",
            "Juiced",
            "Beach Party",
            "T. rex",
            "Striker",
            "Striker Pro",
            "Striker Legend",
            "Singularity",
            "Supernova I",
            "Supernova II",
            "Supernova III",
            "Hot Wheels",
        ],
        "paint finish": [
            "Brushed Metal",
            "Corroded Metal",
            "Glossy",
            "Furry",
            "Matte",
            "Metallic",
            "Metallic Pearl",
            "Pearlescent",
            "Semigloss",
            "Toon Matte",
            "Wood",
            "Sun-Damaged",
            "Stainless Steel",
            "Circuit Board",
            "Moon Rock",
            "Cookie Dough",
            "Knitted Yarn",
            "Burlap",
            "Zebra",
            "Pearlescent (Matte)",
            "Skullcap",
            "Metallic (Smooth)",
            "Metallic Pearl (Smooth)",
            "Anodized",
            "Canvas",
            "Metallic (Rough)",
            "Metallic Flake",
        ],
        "player banner": [
            "Mrs. Avocado",
            "Blueprint",
            "Calculated",
            "Beaten Egg",
            "Crisscross",
            "Sharp Flames",
            "Old Flame",
            "Doughnut Eater",
            "Crystal",
            "Pigeon",
            "Ice Pop",
            "Soccer Splash",
            "Topographic",
            "Turtle",
            "Ball King",
            "Call Sign RL",
            "Triangle",
            "Shattered",
            "Solar System",
            "Taxi",
            "Moai",
            "Shooting Star",
            "Vice",
            "Triplicate",
            "Block",
            "Coral",
            "Feathered",
            "Dendritic",
            "Dead Serious",
            "Ishihara",
            "Island Scales",
            "Lift-Off",
            "Standard",
            "Nice Slice",
            "Unicorn",
            "Starbase ARC",
            "Burnout",
            "S'mored",
            "Howler",
            "Winning Streak",
            "Migraine",
            "Soccer Ball",
            "Season 5 - Bronze (Dragon)",
            "Season 5 - Champion (Dragon)",
            "Season 5 - Diamond (Dragon)",
            "Season 5 - Gold (Dragon)",
            "Season 5 - Platinum (Dragon)",
            "Season 5 - Silver (Dragon)",
            "Zombie",
            "Winter's Warmth",
            "Salty",
            "Season 5 - Grand Champion (Dragon)",
            "Holiday Gifts",
            "Season 5 - Bronze",
            "Season 5 - Champion",
            "Season 5 - Diamond",
            "Season 5 - Gold",
            "Season 5 - Grand Champion",
            "Season 5 - Platinum",
            "Season 5 - Silver",
            "DC Comics",
            "Blast Off",
            "Game On",
            "RL Esports",
            "Psyonix",
            "WWE Monday Night RAW",
            "WWE NXT",
            "WWE",
            "WWE SmackDown Live!",
            "WWE WrestleMania 34",
            "S. Watercolour",
            "Battle-Cars Anniversary",
            "Mr DNA",
            "Jurassic Park",
            "Jurassic World",
            "Season 7 - Tier 1",
            "Season 7 - Tier 6",
            "Season 7 - Tier 5",
            "Season 7 - Tier 3",
            "Season 7 - Tier 7",
            "Season 7 - Tier 4",
            "Season 7 - Tier 2",
            "Birthday Bash",
            "Rocket Labs",
            "Soccar Nebula",
            "Hoagie",
            "Shark Attack",
            "Sushi Roll",
            "Trash It!",
            "Hot Wheels 50th",
            "CRL Eastern",
            "CRL Northern",
            "CRL Southern",
            "CRL Western",
        ],
        toppers: [
            "(Alpha Reward) Gold Cap",
            "Propellerhead",
            "Bobby Helmet",
            "Royal Crown",
            "Devil Horns",
            "Fez",
            "Fire Helmet",
            "Halo",
            "Hard Hat",
            "Mariachi Hat",
            "Pirate's Hat",
            "Pizza Topper",
            "Cherry Top",
            "Sombrero",
            "Taxi Topper",
            "Top Hat",
            "Brünnehilde",
            "Witch's Hat",
            "Wizard Hat",
            "Foam Hat",
            "Drink Helmet",
            "Pixelated Shades",
            "Tiara",
            "Boombox",
            "Pumpkin",
            "Locomotive",
            "Shark Fin",
            "Cavalier",
            "Mohawk",
            "Blitzen",
            "Sad Sapling",
            "Santa",
            "Light Bulb",
            "Portal - Cake",
            "Cow Skull",
            "Season 1 - Bronze",
            "Season 1 - Gold",
            "Season 1 - Platinum",
            "Season 1 - Silver",
            "Work Boot",
            "Captain's Hat",
            "Homburg",
            "Brodie Helmet",
            "Fruit Hat",
            "Bowler",
            "Police Hat",
            "Traffic Cone",
            "Chef's Hat",
            "Cockroach",
            "Paper Boat",
            "Rasta",
            "Plunger",
            "Shuriken",
            "Antlers",
            "Beret",
            "Biker Cap",
            "Graduation Cap",
            "Rhino Horns",
            "Mouse Trap",
            "Birthday Cake",
            "Derby",
            "Deerstalker",
            "Chainsaw",
            "deadmau5",
            "Wildcat Ears",
            "Little Bow",
            "Party Hat",
            "Worms W.M.D.",
            "Baseball Cap (F)",
            "Cattleman",
            "Ivy Cap",
            "Baseball Cap (B)",
            "White Hat",
            "Trucker Hat",
            "Pork Pie",
            "Visor",
            "Day of the Tentacle",
            "Black Market Preview",
            "Clamshell",
            "Bone King",
            "Ghost",
            "Fishbowl",
            "Helper Elf",
            "Shark Bite",
            "Bunny Ears",
            "Easter Basket",
            "Hustle Brows",
            "Mount Champion",
            "Mr. Meeseeks",
            "Mr. PBH",
            "Cromulon",
            "Latte",
            "Succulents",
            "Sushi Nigiri",
            "Uncle Sam",
            "Butterfly",
            "Rainbow",
            "Scarecrow Jack",
            "Surfboard",
            "MMS Headphones",
            "Jack-in-the-Box",
            "Macaron",
            "Undying Love",
            "Grave Robber",
            "Mr. Banana",
            "Stegosaur",
            "Worried Watermelon",
            "Rooster Comb",
            "Happy Penguin",
            "Bycocket",
            "Dragon Wings",
            "Catfish",
            "Hawaiian Lei",
            "Sad Strawberry",
            "Mr. Hot Pepper",
            "Chafed Cherry",
            "Mr. Hot Dog",
            "Octopus",
            "Hotcakes",
            "Campaign Hat",
            "Holiday Bow",
            "Angel Wings",
            "Fallen Tree",
            "Snowboards",
            "Gargoyle",
            "Little Elephant",
            "Little Sloth",
            "Little Owl",
            "Little Cow",
            "Little Bunny",
            "Little Dog",
            "Mr. Pineapple",
            "Goldfish",
            "GG the Clown",
            "Stoic Muffin",
            "Two-Timer",
            "Dizzy Birds",
            "Swim Ring",
            "Palm Tree",
            "Kayak",
            "Buzzer",
            "Great White",
            "Sand Castle",
            "Breakout: What A Save!",
            "Jurassic Park Hard Hat",
            "LFT",
            "Drip Drop",
            "Jolt Bangle I",
            "Jolt Bangle II",
            "Jolt Bangle III",
            "Phoenix Wings I",
            "Phoenix Wings II",
            "Phoenix Wings III",
            "Hot Wheels Spider",
            "Hot Wheels Snake",
            "Hot Wheels Gorilla",
            "Hot Wheels RC Rivals",
            "Monstercat Uncaged",
        ],
        trails: [
            "Grass",
            "Russia",
            "Carbon Fiber",
            "Toon Glossy",
            "Toon Wood",
            "Gassy Mexican",
            "Guinea Bissau",
            "ROBO-Visor",
            "New Year's 2017",
            "Triplex",
            "Revenant",
            "Lightspeed",
            "Blazer",
            "Friction",
            "Glossy Block",
            "'80s Grad",
            "Season 4 - Bronze",
            "Season 4 - Silver",
            "Season 4 - Gold",
            "Season 4 - Platinum",
            "Season 4 - Diamond",
            "Season 4 - Champion",
            "Heart Glasses",
            "Hot Rocks",
            "Woofless",
            "Hallowtide",
            "Zigzag",
            "Candy Cane",
            "Cutlass",
            "Luminous",
            "Lustrum X10",
            "EQ",
            "EKG-OMG",
            "Toon Hydro",
            "Inverness",
            "Binary",
            "Laser Wave I",
            "Laser Wave II",
            "Laser Wave III",
            "Bossfight",
        ],
        wheels: [
            "(Alpha Reward) Goldstone",
            "Tunica",
            "Bender",
            "Lucci",
            "Tomahawk",
            "Dieci",
            "Almas",
            "Stallion",
            "Rat Rod",
            "Trahere",
            "Stern",
            "Lowrider",
            "Neptune",
            "Spyder",
            "Foreman",
            "Veloce",
            "Alchemist",
            "Mountaineer",
            "OEM",
            "Tempest",
            "Octavian",
            "Invader",
            "Vortex",
            "Falco",
            "Cristiano",
            "Spinner",
            "Photon",
            "Servergate",
            "Carriage",
            "COG",
            "Puma",
            "Voltaic",
            "Zeta",
            "Lobo",
            "Pulsus",
            "Looper",
            "Discotheque",
            "Equalizer",
            "Rhino",
            "Chakram",
            "Troika",
            "Asterias",
            "FSL",
            "Spiralis",
            "Zomba",
            "ARA-51",
            "Chrono",
            "Roulette",
            "Kalos",
            "Diablo",
            "WW5SP",
            "FGSP",
            "Septem",
            "OH5",
            "Draco",
            "K2",
            "ZT-17",
            "Apex",
            "Ninja",
            "Season 3 - Prospect",
            "Season 3 - Challenger",
            "Season 3 - Star",
            "Season 3 - Champion",
            "Fireplug",
            "Gearlock",
            "Quimby",
            "GA-819 HB",
            "Turbine",
            "Hikari P5",
            "Hiro",
            "SLK",
            "Sanchez DC-137",
            "Yuzo",
            "Gaiden",
            "Nipper",
            "Masato",
            "Decennium Pro",
            "Pinwheel",
            "Clockwork",
            "Doughnut",
            "Saptarishi",
            "Mario NSR",
            "Cauldron",
            "Peppermint",
            "Christmas Wreath",
            "Grimalkin",
            "Wonderment",
            "Z-Plate",
            "Infinium",
            "Sovereign Pro",
            "Aether",
            "Illuminata",
            "Season 6 - Bronze",
            "Season 6 - Silver",
            "Season 6 - Gold",
            "Season 6 - Platinum",
            "Season 6 - Diamond",
            "Season 6 - Champion",
            "Razzle",
            "Balla-Carrà",
            "REEVRB",
            "Diomedes",
            "Kyrios",
            "Hypnotik",
            "Cruxe",
            "Santa Fe",
            "Sovereign A/T",
            "Centro",
            "Dynamo",
            "SARPBC-10",
            "Meridian",
            "Watermelon",
            "Libertine",
            "Mothership Pro",
            "Thread-X2",
            "Reactor",
            "Aero Mage",
            "Troublemaker I",
            "Troublemaker II",
            "Troublemaker III",
            "Troublemaker IV",
            "Capacitor I",
            "Capacitor II",
            "Capacitor III",
            "Capacitor IV",
            "Pyramidia",
            "Hot Hot Wheels"             
        ]
}