export default [
    {
        id: 1,
        category: "body",
        name: "octane",
        color: "titanium white",
        rarity: "common",
    },
    {
        id: 2,
        category: "wheels",
        name: "drn",
        color: "burnt orange",
        rarity: "premium",
    },
    {
        id: 3,
        category: "paint finish",
        name: "furry",
        color: null,
        rarity: "import",
    },
    {
        id: 4,
        category: "decal",
        name: "dissolver",
        color: null,
        rarity: "black market",
    },
    {
        id: 5,
        category: "body",
        name: "octane",
        color: "titanium white",
        rarity: "common",
    },
    {
        id: 6,
        category: "wheels",
        name: "drn",
        color: "burnt orange",
        rarity: "premium",
    },
    {
        id: 7,
        category: "paint finish",
        name: "furry",
        color: null,
        rarity: "import",
    },
    {
        id: 8,
        category: "decal",
        name: "dissolver",
        color: null,
        rarity: "black market",
    },
    {
        id: 9,
        category: "body",
        name: "octane",
        color: "titanium white",
        rarity: "common",
    },
    {
        id: 10,
        category: "wheels",
        name: "drn",
        color: "burnt orange",
        rarity: "premium",
    },
    {
        id: 11,
        category: "paint finish",
        name: "furry",
        color: null,
        rarity: "import",
    },
    {
        id: 12,
        category: "decal",
        name: "dissolver",
        color: null,
        rarity: "black market",
    }
]