export default [
    {
        id: 1,
        category: "body",
        name: "octane",
        painted: "titanium white",
        rarity: "common",
        special_edition: null,
        certified: null,
    },
    {
        id: 2,
        category: "wheels",
        name: "drn",
        painted: "burnt orange",
        rarity: "premium",
        special_edition: "INFINITE",
        certified: "GOALKEEPER",
    },
    {
        id: 3,
        category: "paint finish",
        name: "furry",
        painted: null,
        rarity: "import",
        special_edition: null,
        certified: null,
    },
    {
        id: 4,
        category: "decal",
        name: "dissolver",
        painted: null,
        rarity: "black market",
        special_edition: null,
        certified: "SHOW-OFF",
    },
    {
        id: 5,
        category: "body",
        name: "octane",
        painted: "titanium white",
        rarity: "common",
        special_edition: null,
        certified: null,
    },
    {
        id: 6,
        category: "wheels",
        name: "drn",
        painted: "burnt orange",
        rarity: "premium",
        special_edition: "INFINITE",
        certified: "AVIATOR",
    },
    {
        id: 7,
        category: "paint finish",
        name: "furry",
        painted: null,
        rarity: "import",
        special_edition: null,
        certified: null,
    },
    {
        id: 8,
        category: "decal",
        name: "dissolver",
        painted: null,
        rarity: "black market",
        special_edition: null,
        certified: "SCORER",
    },
    {
        id: 9,
        category: "body",
        name: "octane",
        painted: "titanium white",
        rarity: "common",
        special_edition: null,
        certified: null,
    },
    {
        id: 10,
        category: "wheels",
        name: "drn",
        painted: "burnt sienna",
        rarity: "premium",
        special_edition: "INFINITE",
        certified: "STRIKER",
    },
    {
        id: 11,
        category: "paint finish",
        name: "furry",
        painted: null,
        rarity: "import",
        special_edition: null,
        certified: null,
    },
    {
        id: 12,
        category: "decal",
        name: "dissolver",
        painted: null,
        rarity: "black market",
        special_edition: null,
        certified: "TURTLE",
    }
    ,
    {
        id: 13,
        category: "wheels",
        name: "daemon-kelpie",
        painted: "saffron",
        rarity: "black market",
        special_edition: "INFINITE",
        certified: "JUGGLER",
    }
]