export default [
    {
        id: 1,
        fname: "David",
        lname: "Bradley",
        dob: "10/31/1983",
        bio: "David's Bio",
        platform: "PC",
        gamertag: "PaperKid",
        rank: "Diamond III",
        division: "I",
        email: "dbradley@gmail.com",
        lft: true,
    },
    {
        id: 2,
        fname: "Ken",
        lname: "Adams",
        dob: "02/03/1999",
        bio: "Ken's Bio",
        platform: "PS4",
        gamertag: "Crooked Nebula",
        rank: "Platinum III",
        division: "III",
        email: "kadams@aol.com",
        lft: true,
    },
    {
        id: 3,
        fname: "Amanda",
        lname: "Pearl",
        dob: "06/20/1989",
        bio: "Amanda's Bio",
        platform: "PC",
        gamertag: "Solid Hydra",
        rank: "Champion II",
        division: "II",
        email: "apearl@yahoo.com",
        lft: false
    }
]